version: '3'

services:
  db:
    image: mysql:5.7
    volumes:
      - "./db_data:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password #change root password
      MYSQL_DATABASE: livezilla
      MYSQL_USER: user
      MYSQL_PASSWORD: password #change user password
    networks:
      - livezilla
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password 
    networks:
      - livezilla
  livezilla:
    depends_on:
      - db
    image: alatas/livezilla-docker:v8.0.1.3
    restart: always
    ports:
      - '8000:8000'
    volumes:
      - "./html:/var/www/html"
    networks:
      - livezilla

networks:
  livezilla: